-- MySQL Script generated by MySQL Workbench
-- Fri Jun  3 00:11:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema media
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema media
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `media` DEFAULT CHARACTER SET utf8 ;
USE `media` ;

-- -----------------------------------------------------
-- Table `media`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `media`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `user_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `mobile_no` VARCHAR(45) NULL,
  `gender` ENUM('male', 'female') NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `update_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `media`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `media`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `body` VARCHAR(255) NOT NULL,
  `category` ENUM('puplic', 'freind') NOT NULL,
  `create_at` DATETIME NOT NULL,
  `update_at` DATETIME NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `media`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `media`.`freinds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `media`.`freinds` (
  `users_id` INT UNSIGNED NOT NULL,
  `friend_id` INT UNSIGNED NOT NULL,
  `create_at` DATETIME NOT NULL DEFAULT now(),
  INDEX `fk_freinds_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_freinds_users2_idx` (`friend_id` ASC) VISIBLE,
  PRIMARY KEY (`users_id`, `friend_id`),
  CONSTRAINT `fk_freinds_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `media`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_freinds_users2`
    FOREIGN KEY (`friend_id`)
    REFERENCES `media`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `media`.`post_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `media`.`post_comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(255) NOT NULL,
  `create_at` DATETIME NOT NULL,
  `posts_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_comment_posts1_idx` (`posts_id` ASC) VISIBLE,
  INDEX `fk_post_comment_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_comment_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `media`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_comment_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `media`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `media`.`post_img`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `media`.`post_img` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_img_posts1_idx` (`posts_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_img_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `media`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `media`.`post_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `media`.`post_likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('like', 'dislike') NULL,
  `create_at` DATETIME NOT NULL DEFAULT now(),
  `posts_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_likes_posts1_idx` (`posts_id` ASC) VISIBLE,
  INDEX `fk_post_likes_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_likes_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `media`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_likes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `media`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
